### PR TITLE
feat: added .find repl-cli method

### PR DESCRIPTION
**Pull request by yeikiu**

### CODE REVIEW

**Comment by trasherdk** [comment]
You are missing a check, if API keys are available. I don't have those.
```node
kraken-repl >> .find XMREUR
{ orderFilter: { descr: { pair: 'XMREUR' } } }
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at getMessageSignature (/home/trasherdk/local/github/ts-kraken/src/rest/private/message_signature.ts:9:31)
    at /home/trasherdk/local/github/ts-kraken/src/rest/private/private_rest_request.ts:22:53
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

In `package.json` you have `resolutions` witch is a `yarn` thing,
pointing to a non-existing package.
```json
,
  "resolutions": {
    "normalize-url": "^6.0.1"
  },
```

Running the `npm run lint:standard` is a mess.

**Comment by yeikiu** [comment]
Thanks for reviewing this again @trasherdk. Great catch with the API keys check there 👍

**Comment by trasherdk** [comment]
The change fixed the crash, but added a warning.

Running `npm run lint:standard | grep repl_cli` yields 27 warnings.  

Some are:
`Expected '===' and instead saw '=='`
`Extra semicolon`
`Trailing spaces not allowed`

**Comment by yeikiu** [comment]
Cheers for the good review! I am not gonna try to down the linting errors to 0 for now but I did fix those I consider were great catches 👍

**Comment by trasherdk** [comment]
Okay, then it LGTM :smiley:

**Pull request merged**
